Update Sylius version compatibility to 1.14
BitBagCommerce/SyliusElasticsearchPlugin pull request #264
Opened 2024-12-10 22:06 UTC by fedorenko22116

Version has been updated, that's all

2025-01-08 02:37 UTC, christopherhero approved these changes

2025-01-08 04:13 UTC, christopherhero requested changes

2025-01-08 04:13 UTC, christopherhero commented on .github/workflows/build.yml
> +        sylius: [ "~1.13.0", "~1.14.0" ]
Please add the same config to `coding_standard.yml` file

2025-01-10 13:56 UTC, JanPalen approved these changes

2025-01-10 14:32 UTC, fedorenko22116 commented on .github/workflows/build.yml
> +        sylius: [ "~1.13.0", "~1.14.0" ]
Done https://github.com/BitBagCommerce/SyliusElasticsearchPlugin/pull/264/files#diff-23bcd199f83782bd46c557da1a512a5e1d2938911bc385c445510b0a71bc3a00R23

2025-01-21 09:43 UTC, christopherhero approved these changes

2025-01-22 00:06 UTC, merged